### ISSUE TITLE
[BUG] it takes forever taking screenshot for some urls

### ISSUE THREAD

**Issue by ajaykulal** [dwisiswant0/go-stare#1]
if list of urls contain some bad URL's which takes forever, it will never process next URL in the list so an option to specify timeout will be helpful.
Thank you for this tool, its really amazing.

**Comment by dwisiswant0** [comment]
Would you please describe terminal output with verbose flag, @ajaykulal?

**Comment by ajaykulal** [comment]
No output 
![Screenshot from 2020-09-26 23-45-08](https://user-images.githubusercontent.com/65899449/94347580-1cc6ac80-0053-11eb-91fb-d12867f487a7.png)

**Comment by ajaykulal** [comment]
This specific url gives 'Connection timed out' error with curl too.
So its not actually issue of go-stare, so an option to handle these timeouts will be helpful, i guess.
