### ISSUE TITLE
[BUG] Image size ZERO KB after geting the Screenshot

### ISSUE THREAD

**Issue by krisk1712** [dwisiswant0/go-stare#3]
**Describe the bug**

The Screenshot is there at ouput folder but no image shwoing only zero kB. 

**To Reproduce**

1.Install go-stare version v0.0.2
2. try an example go-stare -t "http://google.com"
3. you can see the out/ folder that the image file is present but the size to be zero KB
**Expected behavior**

An expected behavior is that domain screenshot has to be present.

**Screenshots**

**Environment (please complete the following information):**

- OS: Mac OS 
- OS version: Catalina 10.15.7
- go-stare version:  v0.0.2

**Additional context**
  nothing the tool is great but need the bug fixes

**Comment by krisk1712** [comment]
Please do look into it.

**Comment by dwisiswant0** [comment]
That's because the timeout limit has exceeded, try increasing the timeout value to 30 with `-T` flag.

Next release will make value 30s as default timeout.
