### ISSUE TITLE
screenshots taken are of 0 bytes

### ISSUE THREAD

**Issue by anushakotha1** [dwisiswant0/go-stare#42]
The screenshots taken are of 0 bytes and not loading

**Comment by nestorwheelock** [comment]
If anyone experiences this issue, maybe they might consider what's missing in their environment.  Not a bug.  Human dependency issue maybe.  The Youtube talk about chromedp is pretty good.  Especially when it comes to discussing the various ways of getting the necessary chrome parts to make it work.  

https://youtu.be/_7pWCg94sKw?t=481

This is super slick.  Thanks for sharing your work and helping me become aware of these tools.  Def an improvement over selenium.
